import type { FastifyPluginAsync } from "fastify";
import { evaluateRoutes } from "../modules/policy/evaluate-routes";
import { policyRoutes } from "../modules/policy/routes";
import { auditRoutes } from "../modules/audit/routes";
import { approvalsRoutes } from "../modules/approvals/routes";
import { metricsRoutes } from "../modules/metrics/routes";
import { eventsRoutes } from "../modules/events/routes";
import { ingestRoutes } from "../modules/ingest/routes";
import { runsRoutes } from "../modules/runs/routes";
import { agentsRoutes } from "../modules/agents/routes";
import { gatewayRoutes } from "../modules/gateway/routes";
import { apiKeyRoutes } from "../modules/apikeys/routes";
import { policiesRoutes } from "../modules/policies/routes";
import { toolsRoutes } from "../modules/tools/routes";
import { auditLogRoutes } from "../modules/auditlog/routes";
import { webhooksRoutes } from "../modules/webhooks/routes";
import { simulationRoutes } from "../modules/simulation/routes";
import { mcpRoutes } from "../modules/mcp/routes";
import { firewallRoutes } from "../modules/firewall/routes";
import { actionsRoutes } from "../modules/actions/routes";
import { alertRoutes } from "../modules/alerts/routes";
import { billingRoutes } from "../modules/billing/routes";
import { onboardingRoutes } from "../modules/onboarding/routes";

export const v1Routes: FastifyPluginAsync = async (app) => {
  await app.register(evaluateRoutes);
  await app.register(policyRoutes, { prefix: "/policies" });
  await app.register(policiesRoutes, { prefix: "/policies/v2" });
  await app.register(auditRoutes, { prefix: "/audit" });
  await app.register(approvalsRoutes, { prefix: "/approvals" });
  await app.register(metricsRoutes, { prefix: "/metrics" });
  await app.register(eventsRoutes, { prefix: "/events" });
  await app.register(ingestRoutes, { prefix: "/ingest" });
  await app.register(runsRoutes, { prefix: "/runs" });
  await app.register(agentsRoutes, { prefix: "/agents" });
  await app.register(gatewayRoutes, { prefix: "/gateway" });
  await app.register(apiKeyRoutes, { prefix: "/api-keys" });
  await app.register(toolsRoutes, { prefix: "/tools" });
  await app.register(auditLogRoutes, { prefix: "/audit-log" });
  await app.register(webhooksRoutes, { prefix: "/webhooks" });
  await app.register(simulationRoutes, { prefix: "/simulation" });
  await app.register(mcpRoutes, { prefix: "/mcp" });
  await app.register(firewallRoutes, { prefix: "/firewall" });
  await app.register(actionsRoutes, { prefix: "/actions" });
  await app.register(alertRoutes, { prefix: "/alerts" });
  await app.register(billingRoutes, { prefix: "/billing" });
  await app.register(onboardingRoutes, { prefix: "/onboarding" });
};
